[colors]
background       = '#303446'
black            = '#51576D'
blue             = '#8CAAEE'
cursor           = '#F2D5CF'
cyan             = '#81C8BE'
foreground       = '#C6D0F5'
green            = '#A6D189'
magenta          = '#F4B8E4'
red              = '#E78284'
tabs             = '#1E1E2E'
tabs-active      = '#B4BEFE'
white            = '#B5BFE2'
yellow           = '#E5C890'
dim-black        = '#51576D'
dim-blue         = '#8CAAEE'
dim-cyan         = '#81C8BE'
dim-foreground   = '#C6D0F5'
dim-green        = '#A6D189'
dim-magenta      = '#F4B8E4'
dim-red          = '#E78284'
dim-white        = '#B5BFE2'
dim-yellow       = '#E5C890'
light-black      = '#626880'
light-blue       = '#8CAAEE'
light-cyan       = '#81C8BE'
light-foreground = '#C6D0F5'
light-green      = '#A6D189'
light-magenta    = '#F4B8E4'
light-red        = '#E78284'
light-white      = '#A5ADCE'
light-yellow     = '#E5C890'
